name: gdal-user
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - geojson=2.5 
  - gdal=3.6 
  - requests=2.28 
  - shapely=1.8 
  - bs4=4.11 
  - lxml=4.9 
  - matplotlib=3.4.3 
  - tkinter
  - pip
