name: Render Wahoo maps
run-name: Rendering Wahoo maps
on: [push] # TODO run as cron
jobs:
  render-maps:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: "19"
    - run: |
        sudo apt-get update
        sudo apt-get install osmium-tool osmosis python3-tk
    - name: Setup Anaconda
      uses: conda-incubator/setup-miniconda@v2
      with: 
        activate-environment: gdal-user
        environment-file: conda-environment.yaml
        auto-activate-base: false
    - run: |
        conda env list
        conda info
    - name: Install wahoomc and build map
      run: |
        conda init
        source /home/runner/.bashrc
        conda activate gdal-user
        pip install wahoomc
        python -m wahoomc cli -co germany
