name: Render Wahoo maps
run-name: Rendering Wahoo maps
on:
  workflow_call:
    inputs:
      country:
        description: "The country to render map data for"
        required: true
        type: string
        default: germany
jobs:
  render-maps:
    runs-on: "ubuntu-latest"
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: "19"
    - run: |
        sudo apt-get update
        sudo apt-get install osmium-tool osmosis python3-tk
    - name: Setup Anaconda
      uses: conda-incubator/setup-miniconda@v2
      with: 
        activate-environment: gdal-user
        environment-file: conda-environment.yaml
        auto-activate-base: false
    - name: Install wahoomc and build map
      run: |
        conda init
        source /home/runner/.bashrc
        conda activate gdal-user
        pip install wahoomc
        echo "Rendering maps for country ${INPUT_COUNTRY}"
        python -m wahoomc cli -co ${INPUT_COUNTRY}
      shell: bash
      env:
        INPUT_COUNTRY: ${{ inputs.country }}
    - name: Archive map data
      run: |
        tar cvzf ${INPUT_COUNTRY}.tar.gz ~/wahooMapsCreatorData/${INPUT_COUNTRY}
      shell: bash
      env:
        INPUT_COUNTRY: ${{ inputs.country }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.country }}.tar.gz
        path: ${{ inputs.country }}.tar.gz
